apiVersion: v1
kind: ConfigMap
metadata:
  name: upload-config
data:
  FLASK_CONFIG: "development"
  FLASK_APP: "core/wsgi.py"
  MAX_FILE_SIZE: "5242880"
  ALLOWED_FILE_EXTENSIONS: '["jpeg", "jpg", "png", "webp"]'
  ALLOWED_FILE_TYPES: '["image/jpeg", "image/png", "image/jpg", "image/webp"]'
  S3_BUCKET_NAME: "dev-attachments"
  PRESIGNED_URL_EXPIRATION_TIME: "300"
