"""Initial migration

Revision ID: 7f5668933324
Revises: 
Create Date: 2026-01-07 17:55:58.420303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f5668933324'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userfilestore',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=60), nullable=True),
    sa.Column('file_key', sa.String(length=1024), nullable=True),
    sa.Column('file_category', sa.String(length=60), nullable=True),
    sa.Column('file_content_type', sa.String(length=70), nullable=True),
    sa.Column('original_file_name', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('userfilestore')
    # ### end Alembic commands ###
