"""Added unique condition for file_key field

Revision ID: db5b72f5a6e0
Revises: 7f5668933324
Create Date: 2026-01-11 15:48:55.347152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db5b72f5a6e0'
down_revision = '7f5668933324'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userfilestore', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['file_key'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userfilestore', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
